Algoritmo "Quadrado da diferença do primeiro valor pelo segundo."

// Data : 27/07/2020

Var

A,B,Diferenca: Inteiro
Quadrado_da_Dif: Real

Inicio

A <- 0
B <- 0
Escreval("Determine o valor de A e B ")
Leia(A, B)
Diferenca <- A - B
Quadrado_da_Dif <- Diferenca ^ 2
Escreval("A diferença de A e B é de: ", Diferenca)
Escreval("O quadrado da diferença de A e B é de: ", Quadrado_da_Dif )


Fimalgoritmo
