algoritmo "A2-Que os jogos comecem 1"
// Data : 16/07/2020

var

  Soma, X: inteiro

inicio

      Escreval("Observe a Expressão a seguir, e digite o valor de X : X+(25-1+(-11+3)+4) ")
          Leia(X)

                 Soma<- X+(25-1+(-11+3)+4)
                        Escreval(" O valor escolhido para corresponder a X é : ", x)
                        Escreval(" O Resultado da Questão é: ", Soma)

fimalgoritmo
