algoritmo "A6-Área do Mapa"
// Data : 17/07/2020

var

   L,C,area:inteiro

inicio

      Escreval("Digite a Largura e o Comprimento do mapa em questão: ")
         Leia(L,C)
            area<- L*C
                Escreval("Os valores digitados foram :")
                Escreval("Largura =  " , L ," ", "Comprimento = " , C)
                   Escreval(" A área do mapa é de: " , area)

fimalgoritmo
