Algoritmo "LC02-01"

// Data atual  : 6/2/2021
Var

   Number1,Number2:inteiro

Inicio

   Number1 <- 0
   Number2 <- 0
   Escreval("Digite 2 inteiros ")
   Leia(Number1,Number2)
   
   Se (Number1 > Number2)entao
      Escreval("O primeiro número é o maior entre os doi valores digitados")
   Senao
      EScreval("O segundo número é o maior entre os doi valores digitados")
   Fimse
Fimalgoritmo
