Algoritmo "LC03-02"

// Data atual  : 11/3/2021
Var
   cont1, cont2,cont3 : inteiro


Inicio
   cont1<-0
   cont2 <-0
   cont3<-0
   Para cont1 de 1 ate 100 passo 1 faca
      Escreval(cont1)
   Fimpara
   Enquanto cont2 < 100 faca
      cont2<- cont2+1
      Escreval(cont2)
   Fimenquanto
   Repita
      cont3 <- cont3+1
      Escreval(cont3)
   ate( cont3 = 100)
Fimalgoritmo