Algoritmo "LC02-11"

// Data atual  : 7/2/2021
Var

   Number, aux:Inteiro


Inicio

   Number<- 0
   Escreval("Digite um número")
   Leia(Number)
   Se(Number>0) entao
      aux <-Number
      // devolva, na tela, a soma de todos os seus algarismos. Por exemplo, ao número 251 corresponderá o valor8 (2 + 5 + 1)
      //Visualg não possui função para essa tarefa de somar algarismos de um inteiro
   Senao
      Escreval("Número inválido")
   Fimse
Fimalgoritmo
