Algoritmo "LC02-06"
// Data atual  : 6/2/2021

Var

   Diferenca,Number1,Number2:inteiro

Inicio


   Number1 <- 0

   Number2 <- 0

   Escreval("Digite 2 inteiros ")

   Leia(Number1,Number2)

   Se (Number1 > Number2)entao
      Diferenca <- Number1-Number2
      Escreval("O primeiro número é o maior entre os doi valores digitados")
      Escreval("A diferença entre eles é :", Diferenca)

   Fimse

Fimalgoritmo